export const topics = [
  // Subjects
  "geography",
  "indian polity",
  "indian constitution",
  "indian history",
  "indian economy",
  "world history",
  "international relations",
  "environment and ecology",
  "current affairs",
  "science and technology",
  "it and computer science",
  "hindi language",

  // Geography
  "physical geography",
  "human geography",
  "geomorphology",
  "climatology",
  "oceanography",
  "biogeography",
  "environmental geography",
  "geopolitics",
  "geographical thought",
  "geographical information system (gis)",
  "remote sensing",
  "environmental impact assessment",
  "conservation geography",

  // Indian Geography
  "geography of india",
  "physical features of india",
  "climate of india",
  "natural resources in india",
  "human geography of india",
  "transport and communication in india",
  "population and settlements in india",
  "regional development in india",

  // Indian Polity and Constitution
  "constitution of india",
  "preamble",
  "fundamental rights",
  "directive principles of state policy",
  "amendments to the constitution",
  "emergency provisions",
  "parliament and state legislatures",
  "union executive",
  "state executive",
  "union judiciary",
  "state judiciary",
  "federalism in india",
  "local government institutions",
  "election system and reforms",
  "constitutional development in india",
  "constitutional amendments and their impact",

  // Constitutional History
  "making of the constitution",
  "constituent assembly debates",
  "salient features of the constitution",
  "evolution of judicial review",
  "landmark judgments",
  "constitutional amendments",
  "constitutional provisions and issues",

  // Indian History
  "ancient india",
  "indus valley civilization",
  "vedic period",
  "mahajanapadas",
  "mauryan empire",
  "gupta empire",
  "post-gupta period",
  "medieval india",
  "delhi sultanate",
  "mughal empire",
  "maratha empire",
  "modern india",
  "british rule in india",
  "indian freedom struggle",
  "revolt of 1857",
  "social and religious reform movements",
  "indian national congress",
  "partition of india",
  "integration of princely states",
  "post-independence consolidation",
  "economic policies and reforms",

  // Indian Economy
  "planning in india",
  "economic reforms",
  "agriculture in india",
  "industrial development",
  "infrastructure and energy",
  "services sector",
  "trade and commerce",
  "monetary and fiscal policy",
  "public finance",
  "budgeting",
  "inflation and deflation",
  "poverty and unemployment",
  "globalization and indian economy",
  "sustainable development goals (sdgs)",

  // World History
  "ancient civilizations",
  "medieval world",
  "renaissance and reformation",
  "colonialism and imperialism",
  "world wars",
  "cold war era",
  "post-cold war era",
  "decolonization",
  "globalization",
  "united nations",
  "international organizations",

  // International Relations
  "india's foreign policy",
  "bilateral relations",
  "multilateral relations",
  "international institutions",
  "diplomatic relations",
  "international law and treaties",
  "global issues and challenges",
  "climate change and diplomacy",
  "trade and commerce relations",

  // Environment and Ecology
  "ecology concepts",
  "biodiversity conservation",
  "climate change",
  "environmental impact assessment",
  "environmental laws and policies",
  "natural resource management",
  "pollution control",
  "wildlife conservation",
  "sustainable development",

  // Current Affairs
  "national issues",
  "international issues",
  "government schemes and initiatives",
  "sports and awards",
  "books and authors",
  "science and technology developments",
  "economic issues",
  "social issues",

  // Science and Technology
  "general science",
  "physics",
  "chemistry",
  "biology",
  "space science",
  "information technology",
  "computer science",
  "artificial intelligence",
  "internet and networking",
  "robotics",
  "nanotechnology",
  "biotechnology",

  // IT and Computer Science
  "computer fundamentals",
  "programming languages",
  "database management systems",
  "operating systems",
  "web technologies",
  "software engineering",
  "cyber security",
  "digital india initiative",
  "e-governance",

  // Hindi Language
  "hindi literature",
  "hindi grammar",
  "translation from english to hindi",
  "essay writing in hindi",
  "proverbs and idioms in hindi",

  // Additional Topics as per UPSC, UPPSC, and UKPSC
  "history of modern india",
  "administrative changes in india",
  "socio-religious movements in india",
  "freedom struggle in india",
  "integration of princely states",
  "post-independence india",
  "social and economic development in india",
  "cultural heritage of india",

  // Uttar Pradesh Specific Topics
  "history of uttar pradesh",
  "geography of uttar pradesh",
  "economy of uttar pradesh",
  "polity of uttar pradesh",
  "social issues in uttar pradesh",
  "current affairs of uttar pradesh",

  // Uttarakhand Specific Topics
  "history of uttarakhand",
  "geography of uttarakhand",
  "economy of uttarakhand",
  "polity of uttarakhand",
  "social issues in uttarakhand",
  "current affairs of uttarakhand",

  // Mics
  "misc",
];
